routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();


Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        return redirect(route('admin.user.index'));
    });
    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('index');
        Route::get('/{item}/action',
            [App\Http\Controllers\Admin\UserController::class, 'action'])->name('action');
        Route::match(['get', 'post'], '/{item}/form',
            [App\Http\Controllers\Admin\UserController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'transaction.', 'prefix' => 'transaction'], function () {
        Route::get('/', [App\Http\Controllers\Admin\TransactionController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'userObject.', 'prefix' => 'object'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectController::class, 'index'])->name('index');
        Route::match(['get', 'post'], '/{item}',
            [App\Http\Controllers\Admin\UserObjectController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'userObjectReview.', 'prefix' => 'review'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectReviewController::class, 'index'])->name('index');
        Route::get('/{item}/approve',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'approve'])->name('approve');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'userObjectBanner.', 'prefix' => 'banner'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'index'])->name('index');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'price.', 'prefix' => 'price'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\PricesController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'support.', 'prefix' => 'support'], function () {
        Route::get('/',
            [\App\Http\Controllers\Admin\SupportController::class, 'index'])->name('index');
        Route::get('/messages/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'getMessages'])->name('messages');
        Route::match(['get', 'post'], '/chat/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'chat'])->name('chat');
        Route::post('/new',
            [\App\Http\Controllers\Admin\SupportController::class, 'new'])->name('new');
    });
});

Route::group(['as' => 'front.'], function () {
    Route::match(['get','post'],'/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index');
    Route::get('/snjat_kottedzh_dlja_vecherinki',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_vecherinki');
    Route::get('/snjat_kottedzh_dlja_svadby',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_svadby');
    Route::get('/snjat_kottedzh_v_leningradskoj_oblasti_s_banej', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.snjat_kottedzh_v_leningradskoj_oblasti_s_banej');
    Route::get('/snjat_kottedzh_v_vyborgskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborgskom_rajone');
    Route::get('/snjat_kottedzh_v_vyborge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborge');
    Route::get('/snjat_kottedzh_v_priozerskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_priozerskom_rajone');
    Route::get('/snjat_kottedzh_v_pushkine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_pushkine');
    Route::get('/snjat_kottedzh_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_gatchine');
    Route::get('/snjat_kottedzh_v_petergofe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_petergofe');
    Route::get('/snjat_kottedzh_v_tosnenskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tosnenskom_rajone');
    Route::get('/snjat_kottedzh_v_tihvine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tihvine');
    Route::get('/snjat_kottedzh_v_sosnovo',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_sosnovo');
    Route::get('/snjat_kottedzh_na_novyj_god',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_na_novyj_god');
    Route::get('/baza_otdyha_v_leningradskoj_oblasti_u_ozera', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.baza_otdyha_v_leningradskoj_oblasti_u_ozera');
    Route::get('/baza_otdyha_s_detmi',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_detmi');
    Route::get('/baza_otdyha_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_gatchine');
    Route::get('/baza_baza_otdyha_vyborg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_baza_otdyha_vyborg');
    Route::get('/baza_otdyha_sosnovyj_bor',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_sosnovyj_bor');
    Route::get('/baza_otdyha_tihvin',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tihvin');
    Route::get('/baza_otdyha_kingisepp',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_kingisepp');
    Route::get('/baza_otdyha_volhov',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_volhov');
    Route::get('/baza_otdyha_tosno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tosno');
    Route::get('/baza_otdyha_lodejnoe_pole',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_lodejnoe_pole');
    Route::get('/baza_otdyha_boksitogorsk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_boksitogorsk');
    Route::get('/baza_otdyha_shlissel_burg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_shlissel_burg');

    Route::get('/snyat_kottedzh_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_posutochno');
    Route::get('/snyat_kottedzh_s_banej',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_banej');
    Route::get('/snyat_kottedzh_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti_posutochno');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti');
    Route::get('/snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti');


    Route::get('/baza_otdyha_v_leningradkoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_leningradkoj_oblasti');
    Route::get('/baza_otdyha_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_bassejnom');
    Route::get('/luchshie_bazy_otdyha_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.luchshie_bazy_otdyha_v_leningradskoj_oblasti');
    Route::get('/baza_otdyha_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_spb');
    Route::get('/baza_otdyha_v_luge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_luge');
    Route::get('/baza_otdyha_otradnoe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_otradnoe');
    Route::get('/baza_otdyha_priozersk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_priozersk');

    Route::get('/zagorodnye_oteli_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_leningradskoj_oblasti');
    Route::get('/zagorodnye_oteli_v_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_spb');

app/Models/UserObjectBanner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserObjectBanner extends Model
{
    protected $fillable = [
        'status_id',
        'position',
        'start_at',
        'end_at',
        'object_id',
    ];

    const STATUS_ACTIVE = 1;
    const STATUS_DELETE = 2;
    const STATUS_ENDED = 3;

    public function userObject()
    {
        return $this->hasOne(UserObject::class, 'id', 'object_id');
    }

    public function getDaysAttribute()
    {
        $meterings = [
            0 => 'дней',
            1 => 'день',
            2 => 'дня',
        ];

        $seconds = strtotime($this->end_at) - strtotime('now');
        if ($seconds <= 0) {
            return 'Завершено';
        } elseif ($seconds >= 86400) {
            $value = ceil($seconds / 86400);
        } else {
            $meterings = [
                0 => 'часов',
                1 => 'час',
                2 => 'часа',
            ];
            $value = ceil($seconds / 3600);
            if ($value <= 0) {
                $value = 1;
            }
        }
        $lastDigits = $value % 100;
        $lastDigits = ($lastDigits >= 20) ? $lastDigits % 10 : $lastDigits;

        if ($lastDigits === 0 ||
            $lastDigits >= 5 && $lastDigits <= 20) {
            $metering = 0;
        } elseif ($lastDigits == 1) {
            $metering = 1;
        } else {
            $metering = 2;
        }

        return "Осталось: $value $meterings[$metering]";
    }

}

app/Http/Controllers/Admin/UserObjectBannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\UserObject;
use App\Models\UserObjectBanner;
use Illuminate\Http\Request;

class UserObjectBannerController extends Controller
{
    public $basicModel = UserObjectBanner::class;
    public $basicView = 'userObjectBanner';

    public function index(Request $request)
    {
        if ($request->isMethod('post')) {
            $uo = UserObject::find($request->get('object_id'));
            if ($uo) {
                $banner = UserObjectBanner::find($request->get('banner_id'));
                $start_at = Date('Y-m-d', strtotime($request->get('start_at')));
                $end_at = Date('Y-m-d', strtotime($request->get('end_at')));
                $data = [
                    'status_id' => UserObjectBanner::STATUS_ACTIVE,
                    'start_at' => $start_at,
                    'end_at' => $end_at,
                    'object_id' => $uo->id,
                    'position' => $request->get('position'),
                ];
                if ($banner) {
                    $banner->update($data);
                } else {
                    UserObjectBanner::create($data);
                }
            }
            return redirect(route("admin.{$this->basicView}.index"));
        }
        $query = $this->basicModel::where('status_id', UserObjectBanner::STATUS_ACTIVE);
        $items = [];
        foreach ($query->get() as $item) {
            $items[$item->position] = $item;
        }
        return view("admin.$this->basicView.index",
            [
                'items' => $items,
            ]
        );
    }

    public function delete(Request $request, UserObjectBanner $item)
    {
        $item->update(['status_id' => UserObjectBanner::STATUS_DELETE]);
        return redirect(route("admin.{$this->basicView}.index"));
    }
}

resources/views/admin/userObjectBanner/partials/item.blade.php
@php
    $uo = $item?$item->userObject:null;
@endphp
<div class="admin-content_banners-list_item">
    <p class="admin-content_title">Размещение №{{$position}}: </p>
    <div class="admin-content_banners-list_container">
        @if(!empty($uo))
            <div class="banner-block">
                <img src="{{$uo->MainPhoto?$uo->MainPhoto->value:''}}">
                <p class="obyavlenie-box_info-title">{{$uo->title}}</p>
                <p class="obyavlenie-box_info-subtitle">{{$uo->address}}</p>
                <p class="banner-block_price">
                    @if($uo->type == 'cottage')
                        <span>{{$uo->object->price_day}}</span> ₽/сутки
                    @else
                        {!! \App\Models\UserObject::PRICE_TYPES[$uo->type][$uo->price_type_id]['price'] !!}
                    @endif
                </p>
            </div>
        @endif
        <div class="banner-form">
            <form method="post">
                <input type="hidden" value="{{$position}}" name="position"/>
                <input type="hidden" value="{{!empty($item)?$item->id:''}}" name="banner_id"/>
                <div class="banner-form_row">
                    <input placeholder="Введите id" name="object_id" value="{{!empty($item)?$item->object_id:''}}">
                    <div class="banner-form_btn">
                        <button class="subprimary-btn">Сохранить</button>
                        @if(!empty($item))
                            <a href="{{route('admin.userObjectBanner.delete',$item->id)}}"
                               class="subprimary-btn _question_alert">Удалить</a>
                        @endif
                    </div>
                </div>
                <div class="banner-form_row">
                    <div class="admin-content_filter-container_date">
                        {{--                        <input type="datetime-local" name="start_at"--}}
                        {{--                               value="{{!empty($item)?str_replace(' ','T',Date('Y-m-d H:i:s',strtotime($item->start_at))):''}}">--}}
                        {{--                        <span>-</span>--}}
                        {{--                        <input type="datetime-local" name="end_at"--}}
                        {{--                               value="{{!empty($item)?str_replace(' ','T',Date('Y-m-d H:i:s',strtotime($item->end_at))):''}}">--}}
                        <input class="datepicker-here" data-timepicker="true" data-time-format='hh:ii' name="start_at"
                               value="{{!empty($item)?Date('d.m.Y H:i',strtotime($item->start_at)):''}}"
                        >
                        <span>-</span>
                        <input class="datepicker-here" data-timepicker="true" data-time-format='hh:ii' name="end_at"
                               value="{{!empty($item)?Date('d.m.Y H:i',strtotime($item->end_at)):''}}"
                        >
                    </div>
                </div>
                @if(!empty($item))
                    <div class="banner-form_row">
                        <div class="banner-form_timeLeft">
                            <img src="{{asset('/img/admin/load.png')}}">
                            <p>{{$item->days}}</p>
                        </div>
                    </div>
                @endif
            </form>
        </div>
    </div>
</div>