routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();


Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        return redirect(route('admin.user.index'));
    });
    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('index');
        Route::get('/{item}/action',
            [App\Http\Controllers\Admin\UserController::class, 'action'])->name('action');
        Route::match(['get', 'post'], '/{item}/form',
            [App\Http\Controllers\Admin\UserController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'transaction.', 'prefix' => 'transaction'], function () {
        Route::get('/', [App\Http\Controllers\Admin\TransactionController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'userObject.', 'prefix' => 'object'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectController::class, 'index'])->name('index');
        Route::match(['get', 'post'], '/{item}',
            [App\Http\Controllers\Admin\UserObjectController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'userObjectReview.', 'prefix' => 'review'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectReviewController::class, 'index'])->name('index');
        Route::get('/{item}/approve',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'approve'])->name('approve');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'userObjectBanner.', 'prefix' => 'banner'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'index'])->name('index');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'price.', 'prefix' => 'price'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\PricesController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'support.', 'prefix' => 'support'], function () {
        Route::get('/',
            [\App\Http\Controllers\Admin\SupportController::class, 'index'])->name('index');
        Route::get('/messages/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'getMessages'])->name('messages');
        Route::match(['get', 'post'], '/chat/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'chat'])->name('chat');
        Route::post('/new',
            [\App\Http\Controllers\Admin\SupportController::class, 'new'])->name('new');
    });
});

Route::group(['as' => 'front.'], function () {
    Route::match(['get','post'],'/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index');
    Route::get('/snjat_kottedzh_dlja_vecherinki',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_vecherinki');
    Route::get('/snjat_kottedzh_dlja_svadby',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_svadby');
    Route::get('/snjat_kottedzh_v_leningradskoj_oblasti_s_banej', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.snjat_kottedzh_v_leningradskoj_oblasti_s_banej');
    Route::get('/snjat_kottedzh_v_vyborgskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborgskom_rajone');
    Route::get('/snjat_kottedzh_v_vyborge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborge');
    Route::get('/snjat_kottedzh_v_priozerskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_priozerskom_rajone');
    Route::get('/snjat_kottedzh_v_pushkine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_pushkine');
    Route::get('/snjat_kottedzh_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_gatchine');
    Route::get('/snjat_kottedzh_v_petergofe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_petergofe');
    Route::get('/snjat_kottedzh_v_tosnenskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tosnenskom_rajone');
    Route::get('/snjat_kottedzh_v_tihvine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tihvine');
    Route::get('/snjat_kottedzh_v_sosnovo',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_sosnovo');
    Route::get('/snjat_kottedzh_na_novyj_god',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_na_novyj_god');
    Route::get('/baza_otdyha_v_leningradskoj_oblasti_u_ozera', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.baza_otdyha_v_leningradskoj_oblasti_u_ozera');
    Route::get('/baza_otdyha_s_detmi',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_detmi');
    Route::get('/baza_otdyha_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_gatchine');
    Route::get('/baza_baza_otdyha_vyborg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_baza_otdyha_vyborg');
    Route::get('/baza_otdyha_sosnovyj_bor',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_sosnovyj_bor');
    Route::get('/baza_otdyha_tihvin',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tihvin');
    Route::get('/baza_otdyha_kingisepp',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_kingisepp');
    Route::get('/baza_otdyha_volhov',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_volhov');
    Route::get('/baza_otdyha_tosno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tosno');
    Route::get('/baza_otdyha_lodejnoe_pole',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_lodejnoe_pole');
    Route::get('/baza_otdyha_boksitogorsk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_boksitogorsk');
    Route::get('/baza_otdyha_shlissel_burg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_shlissel_burg');

    Route::get('/snyat_kottedzh_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_posutochno');
    Route::get('/snyat_kottedzh_s_banej',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_banej');
    Route::get('/snyat_kottedzh_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti_posutochno');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti');
    Route::get('/snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti');


    Route::get('/baza_otdyha_v_leningradkoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_leningradkoj_oblasti');
    Route::get('/baza_otdyha_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_bassejnom');
    Route::get('/luchshie_bazy_otdyha_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.luchshie_bazy_otdyha_v_leningradskoj_oblasti');
    Route::get('/baza_otdyha_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_spb');
    Route::get('/baza_otdyha_v_luge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_luge');
    Route::get('/baza_otdyha_otradnoe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_otradnoe');
    Route::get('/baza_otdyha_priozersk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_priozersk');

    Route::get('/zagorodnye_oteli_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_leningradskoj_oblasti');
    Route::get('/zagorodnye_oteli_v_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_spb');

resources/views/admin/partials/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/admin.js') }}" defer></script>

    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBY63MMSWBJpdwdawp4s5tRcmnl_SjWpus&libraries=places&v=weekly&region=RU&language=ru"
    ></script>
    <!-- Styles -->
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet">

</head>
<body>
<div class="admin_sec cabinet_sec">
    @include('admin.partials.header')
    @yield('content')
    @include('admin.partials.routes')
</div>
</body>
</html>

resources/views/admin/partials/header.blade.php
<header>
    <div class="container">
        <div class="header-box">
            <div class="header-box_logo">
                <a href="{{route('front.index')}}" class="header-box_logo">
                    <img src="{{asset('/img/front/logo_header.svg')}}">
                </a>
            </div>
            <div class="header-box_menu">
                <div class="header-box_menu-btn">
                    <a href="{{route('front.index')}}" class="primary-btn">На сайт</a>
                </div>
            </div>
            <div class="menu-drop">
                <div class="menu-drop_burger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <ul class="menu-drop_list">
                    <li class="menu-drop_list-item"><a href="{{route('front.index')}}">На сайт</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

resources/views/admin/partials/pagination.blade.php
@php
    $query_search = '';
    $count = 0;
    foreach (!empty($filters)?$filters:[] as $id => $value) {
        if (is_array($value)) {
            foreach ($value as $v){
                $query_search .= '&'.$id . '[]=' . $v;
                $count++;
            }
        } else {
            $query_search .= '&'.$id . '=' . $value;
            $count++;
        }
    }
    $max_pages = 7;
@endphp
@if($pagination->currentPage() > 1 || $pagination->hasMorePages())
    <ul class="_pagination">
        @if($pagination->currentPage() >= 2)
            <li>
                <a href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() - 1}}{{$query_search}}">«</a>
            </li>
        @endif
        @php
            $left_pages = $pagination->lastPage() - $pagination->currentPage();
            if($left_pages>$max_pages){
                $prev_pages = $pagination->currentPage() > $max_pages ?  $max_pages : $pagination->currentPage() - 1;
            }else{
                $prev_pages = $pagination->currentPage() > ($max_pages + $max_pages - $left_pages) ? ($max_pages + $max_pages - $left_pages) : $pagination->currentPage() - 1;
            }

            $next_pages = $pagination->lastPage() > $pagination->currentPage() + 1 ? ($left_pages) : 2;
            $next_pages = $next_pages > ($max_pages + $max_pages - $prev_pages) ? ($max_pages + $max_pages - $prev_pages) : $next_pages;
        @endphp

        @for($i = $prev_pages; $i >= 1; $i--)
            @php
                $page = $pagination->currentPage() - $i;
            @endphp
            @if($page <= $pagination->lastPage())
                <li>
                    <a href="{{route(Route::current()->getName())}}?page={{$page}}{{$query_search}}">{{$page}}</a>
                </li>
            @endif
        @endfor
        @if($pagination->currentPage() <= $pagination->lastPage())
            <li class="active">
                <a>{{$pagination->currentPage()}}</a>
            </li>
        @endif

        @for($i = 1; $i <= $next_pages; $i++)
            @php
                $page = $pagination->currentPage() + $i;
            @endphp
            @if($page <= $pagination->lastPage())
                <li>
                    <a href="{{route(Route::current()->getName())}}?page={{$page}}{{$query_search}}">{{$page}}</a>
                </li>
            @endif
        @endfor


        @if($pagination->hasMorePages())
            <li>
                <a href="{{route(Route::current()->getName())}}?page={{$pagination->currentPage() + 1}}{{$query_search}}">»</a>
            </li>
        @endif
    </ul>
@endif

resources/views/admin/partials/routes.blade.php
<input type="hidden" id="_route_current" value="{{Route::current()->getName()}}"/>
<input type="hidden" value="{{route('front.cabinet.object.uploadPhoto')}}" id="_api_cabinet_object_uploadPhoto"/>
<input type="hidden" value="{{route('admin.support.messages',['item'=>1])}}" id="_api_render_support_messages"/>

resources/views/admin/partials/sidebar.blade.php
@include('admin.partials.sidebarMenu')
<div class="sidebar-menu">
    <input id="menu" type="checkbox"/>
    <label for="menu">
        <span></span>
        <span></span>
        <span></span>
    </label>
    <article>
        @include('admin.partials.sidebarMenu')
    </article>
</div>

resources/views/admin/partials/sidebarMenu.blade.php
<ul class="sidebar-list">
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.user.')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.user.index')}}">Пользователи</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.userObject.index')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.userObject.index')}}">Объявления</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.costPlacement')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.price.index')}}">Стоимость размещения</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.price.')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.transaction.index')}}">Транзакции</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.userObjectBanner.index')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.userObjectBanner.index')}}">Рекламные баннеры</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.userObjectReview.index')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.userObjectReview.index')}}">Модерация отзывов</a></li>
    <li class="sidebar-list_item {{strpos(Route::current()->getName(),'admin.support.index')!==false?'sidebar-list_item-active':''}}">
        <a href="{{route('admin.support.index')}}">Сообщения</a></li>
</ul>