routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();


Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        return redirect(route('admin.user.index'));
    });
    Route::group(['as' => 'user.', 'prefix' => 'user'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('index');
        Route::get('/{item}/action',
            [App\Http\Controllers\Admin\UserController::class, 'action'])->name('action');
        Route::match(['get', 'post'], '/{item}/form',
            [App\Http\Controllers\Admin\UserController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'transaction.', 'prefix' => 'transaction'], function () {
        Route::get('/', [App\Http\Controllers\Admin\TransactionController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'userObject.', 'prefix' => 'object'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectController::class, 'index'])->name('index');
        Route::match(['get', 'post'], '/{item}',
            [App\Http\Controllers\Admin\UserObjectController::class, 'form'])->name('form');
    });
    Route::group(['as' => 'userObjectReview.', 'prefix' => 'review'], function () {
        Route::get('/', [App\Http\Controllers\Admin\UserObjectReviewController::class, 'index'])->name('index');
        Route::get('/{item}/approve',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'approve'])->name('approve');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectReviewController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'userObjectBanner.', 'prefix' => 'banner'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'index'])->name('index');
        Route::get('/{item}/delete',
            [App\Http\Controllers\Admin\UserObjectBannerController::class, 'delete'])->name('delete');
    });
    Route::group(['as' => 'price.', 'prefix' => 'price'], function () {
        Route::match(['get', 'post'], '/',
            [App\Http\Controllers\Admin\PricesController::class, 'index'])->name('index');
    });

    Route::group(['as' => 'support.', 'prefix' => 'support'], function () {
        Route::get('/',
            [\App\Http\Controllers\Admin\SupportController::class, 'index'])->name('index');
        Route::get('/messages/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'getMessages'])->name('messages');
        Route::match(['get', 'post'], '/chat/{item}',
            [\App\Http\Controllers\Admin\SupportController::class, 'chat'])->name('chat');
        Route::post('/new',
            [\App\Http\Controllers\Admin\SupportController::class, 'new'])->name('new');
    });
});

Route::group(['as' => 'front.'], function () {
    Route::match(['get','post'],'/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index');
    Route::get('/snjat_kottedzh_dlja_vecherinki',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_vecherinki');
    Route::get('/snjat_kottedzh_dlja_svadby',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_dlja_svadby');
    Route::get('/snjat_kottedzh_v_leningradskoj_oblasti_s_banej', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.snjat_kottedzh_v_leningradskoj_oblasti_s_banej');
    Route::get('/snjat_kottedzh_v_vyborgskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborgskom_rajone');
    Route::get('/snjat_kottedzh_v_vyborge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_vyborge');
    Route::get('/snjat_kottedzh_v_priozerskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_priozerskom_rajone');
    Route::get('/snjat_kottedzh_v_pushkine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_pushkine');
    Route::get('/snjat_kottedzh_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_gatchine');
    Route::get('/snjat_kottedzh_v_petergofe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_petergofe');
    Route::get('/snjat_kottedzh_v_tosnenskom_rajone',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tosnenskom_rajone');
    Route::get('/snjat_kottedzh_v_tihvine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_tihvine');
    Route::get('/snjat_kottedzh_v_sosnovo',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_v_sosnovo');
    Route::get('/snjat_kottedzh_na_novyj_god',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snjat_kottedzh_na_novyj_god');
    Route::get('/baza_otdyha_v_leningradskoj_oblasti_u_ozera', [
        App\Http\Controllers\Front\HomeController::class,
        'index'
    ])->name('index.baza_otdyha_v_leningradskoj_oblasti_u_ozera');
    Route::get('/baza_otdyha_s_detmi',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_detmi');
    Route::get('/baza_otdyha_v_gatchine',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_gatchine');
    Route::get('/baza_baza_otdyha_vyborg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_baza_otdyha_vyborg');
    Route::get('/baza_otdyha_sosnovyj_bor',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_sosnovyj_bor');
    Route::get('/baza_otdyha_tihvin',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tihvin');
    Route::get('/baza_otdyha_kingisepp',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_kingisepp');
    Route::get('/baza_otdyha_volhov',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_volhov');
    Route::get('/baza_otdyha_tosno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_tosno');
    Route::get('/baza_otdyha_lodejnoe_pole',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_lodejnoe_pole');
    Route::get('/baza_otdyha_boksitogorsk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_boksitogorsk');
    Route::get('/baza_otdyha_shlissel_burg',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_shlissel_burg');

    Route::get('/snyat_kottedzh_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_posutochno');
    Route::get('/snyat_kottedzh_s_banej',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_banej');
    Route::get('/snyat_kottedzh_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti_posutochno',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti_posutochno');
    Route::get('/snyat_kottedzh_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_v_leningradskoj_oblasti');
    Route::get('/snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.snyat_kottedzh_s_bassejnom_v_leningradskoj_oblasti');


    Route::get('/baza_otdyha_v_leningradkoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_leningradkoj_oblasti');
    Route::get('/baza_otdyha_s_bassejnom',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_s_bassejnom');
    Route::get('/luchshie_bazy_otdyha_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.luchshie_bazy_otdyha_v_leningradskoj_oblasti');
    Route::get('/baza_otdyha_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_spb');
    Route::get('/baza_otdyha_v_luge',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_v_luge');
    Route::get('/baza_otdyha_otradnoe',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_otradnoe');
    Route::get('/baza_otdyha_priozersk',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.baza_otdyha_priozersk');

    Route::get('/zagorodnye_oteli_v_leningradskoj_oblasti',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_leningradskoj_oblasti');
    Route::get('/zagorodnye_oteli_v_spb',
        [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index.zagorodnye_oteli_v_spb');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    const TYPE_USER = 1;
    const TYPE_OWNER = 2;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'is_active',
        'balance',
        'type_id',
        'phone'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function objects()
    {
        return $this->hasMany(UserObject::class, 'user_id', 'id');
    }

    public function getUnreadDialogCountAttribute()
    {
        if ($this->type_id == self::TYPE_OWNER) {
            $count = ObjectDialog::whereIn('parent_id',
                $this->objects()->get('id')->pluck('id')->toArray())->where('object_new_messages', '>=',
                1)->count();
            $item = SupportDialog::firstOrCreate([
                'user_id' => Auth::id(),
            ]);
            $count_support = $item->user_new_messages;
            return $count + $count_support;
        } else {
            return ObjectDialog::where('user_new_messages', '>=', 1)->where('user_id', Auth::id())->count();
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Transaction;
use App\Models\TransactionUserRefill;
use App\Models\TransactionUserWithdrawal;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public $basicModel = User::class;
    public $basicView = 'user';

    public function index(Request $request)
    {
        $query = $this->basicModel::query();
        $filters = [
            'is_active' => $request->get('is_active'),
            'type_id' => $request->get('type_id'),
            'search_field' => $request->get('search_field'),
            'search_text' => $request->get('search_text'),
        ];
        if (!empty($filters['search_text']) && !empty($filters['search_field'])) {
            $query->where($filters['search_field'], 'LIKE', "%{$filters['search_text']}%");
        }
        if (!empty($filters['is_active'])) {
            $query->where('is_active', $filters['is_active'] == 'true' ? 1 : 0);
        }
        if (!empty($filters['type_id'])) {
            $query->where('type_id', $filters['type_id']);
        }

        return view("admin.$this->basicView.index",
            [
                'pagination' => $query->paginate('10', ['*'], 'page', $request->get('page')),
                'filters' => $filters
            ]
        );
    }

    public function action(Request $request, User $item)
    {
        switch ($request->get('action')) {
            case 'active':
                $item->update(['is_active' => 1]);
                break;
            case 'inactive':
                $item->update(['is_active' => 0]);
                break;
            case 'delete':
                $item->delete();
                break;
        }
        return redirect(route("admin.$this->basicView.index"));
    }

    public function form(Request $request, User $item)
    {
        if ($request->isMethod('post')) {
            $data = $request->only(['first_name', 'last_name', 'phone', 'email']);
            $data['phone'] = '+' . preg_replace('/[^0-9]+/', '', trim(($data['phone'] ?? ''), " '"));
            $item->update($data);
            $balance = intval($request->get('balance', $item->balance));
            if ($balance !== $item->balance) {
                if ($balance > $item->balance) {
                    $transaction = Transaction::create([
                        'user_id' => $item->id,
                        'type_id' => Transaction::TYPE_USER_REFILL,
                        'method_id' => Transaction::METHOD_BALANCE,
                        'amount' => $balance - $item->balance,
                        'comment' => 'Пополнение администратором №' . Auth::id()
                    ]);
                    TransactionUserRefill::create([
                        'transaction_id' => $transaction->id,
                    ]);
                } elseif ($balance < $item->balance) {
                    $transaction = Transaction::create([
                        'user_id' => $item->id,
                        'type_id' => Transaction::TYPE_USER_WITHDRAWAL,
                        'method_id' => Transaction::METHOD_BALANCE,
                        'amount' => $item->balance - $balance,
                        'comment' => 'Списание администратором №' . Auth::id()
                    ]);
                    TransactionUserWithdrawal::create([
                        'transaction_id' => $transaction->id,
                    ]);
                }
                $item->update(['balance' => $balance]);
            }
            return redirect(route("admin.$this->basicView.form", $item->id));
        }
        return view("admin.$this->basicView.form", ['item' => $item]);
    }
}

resources/views/admin/user/form.blade.php
@extends('admin.partials.app')

@section('content')

    <div class="container">
        <div class="admin-wrapper">
            <div class="sidebar">
                @include('admin.partials.sidebar')
            </div>
            <div class="admin-content">

                <div class="settings">
                    <form class="user-edit" method="post">
                        <label>
                            <div class="info">
                                <span>Имя</span>
                            </div>
                            <input type="text" required value="{{$item->first_name}}" name="first_name">
                        </label>
                        <label>
                            <div class="info">
                                <span>Фамилия</span>
                            </div>
                            <input type="text" required value="{{$item->last_name}}" name="last_name">
                        </label>
                        <label>
                            <div class="info">
                                <span>Телефон</span>
                            </div>
                            <input type="text" value="{{$item->phone}}" name="phone">
                        </label>
                        <label>
                            <div class="info">
                                <span>Адрес электронной почты </span>
                            </div>
                            <input type="email" required value="{{$item->email}}" name="email">
                        </label>
                        <label>
                            <div class="info">
                                <span>Баланс</span>
                            </div>
                            <input type="number" value="{{$item->balance}}" name="balance">
                        </label>
                        <div class="user-edit_btns">
                            <button class="primary-btn">
                                Сохранить
                            </button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.partials.app')

@section('content')

    <div class="container">
        <div class="admin-wrapper">
            <div class="sidebar">
                @include('admin.partials.sidebar')
            </div>
            <div class="admin-content">

                <div class="admin-content_filter">
                    <form action="#">
                        <div class="admin-content_filter-row">
                            <p>Поиск пользователя по:</p>
                            <div class="admin-content_filter-container">
                                <select name="search_field">
                                    <option value="id">ID пользователя</option>
                                    <option
                                            value="first_name" {{!empty($filters['search_field']) && $filters['search_field'] == 'first_name'?'selected':''}}>
                                        Имя
                                    </option>
                                    <option
                                            value="last_name" {{!empty($filters['search_field']) && $filters['search_field'] == 'last_name'?'selected':''}}>
                                        Фамилия
                                    </option>
                                    <option
                                            value="email" {{!empty($filters['search_field']) && $filters['search_field'] == 'email'?'selected':''}}>
                                        Почта
                                    </option>
                                </select>
                                <input placeholder="Введите значение" name="search_text"
                                       value="{{!empty($filters['search_text'])?$filters['search_text']:''}}">
                                <button class="subprimary-btn">Найти</button>
                            </div>
                        </div>
                        <div class="admin-content_filter-row">
                            <p>Статус пользователя:</p>
                            <div class="admin-content_filter-container">
                                <p class="form-radio">
                                    <input type="radio" id="all-user" name="is_active"
                                           value="" {{empty($filters['is_active'])?'checked':''}}>
                                    <label for="all-user">Все</label>
                                </p>
                                <p class="form-radio">
                                    <input type="radio" id="active-user" name="is_active"
                                           value="true" {{!empty($filters) && $filters['is_active'] == 'true'?'checked':''}}>
                                    <label for="active-user">Активный</label>
                                </p>
                                <p class="form-radio">
                                    <input type="radio" id="inactive-user" name="is_active"
                                           value="false" {{!empty($filters) && $filters['is_active'] == 'false'?'checked':''}}>
                                    <label for="inactive-user">Заблокированный</label>
                                </p>
                            </div>
                        </div>
                        <div class="admin-content_filter-row">
                            <p>Тип пользователя:</p>
                            <div class="admin-content_filter-container">
                                <p class="form-radio">
                                    <input type="radio" id="all-type" name="type_id"
                                           value="" {{empty($filters['type_id'])?'checked':''}}>
                                    <label for="all-type">Все</label>
                                </p>
                                <p class="form-radio">
                                    <input type="radio" id="type_1-user" name="type_id"
                                           value="{{\App\Models\User::TYPE_USER}}" {{!empty($filters) && $filters['type_id'] == 1?'checked':''}}>
                                    <label for="type_1-user">Пользователь</label>
                                </p>
                                <p class="form-radio">
                                    <input type="radio" id="type_2-user" name="type_id"
                                           value="{{\App\Models\User::TYPE_OWNER}}" {{!empty($filters) && $filters['type_id'] == 2?'checked':''}}>
                                    <label for="type_2-user">Владелец</label>
                                </p>
                            </div>
                        </div>
                        {{--                        <div class="admin-content_filter-row">--}}
                        {{--                            <p>Тип объявлений:</p>--}}
                        {{--                            <div class="admin-content_filter-container">--}}
                        {{--                                <p class="form-radio">--}}
                        {{--                                    <input type="radio" id="cottage" name="users-ad_type">--}}
                        {{--                                    <label for="cottage">Коттеджи</label>--}}
                        {{--                                </p>--}}
                        {{--                                <p class="form-radio">--}}
                        {{--                                    <input type="radio" id="hotel" name="users-ad_type">--}}
                        {{--                                    <label for="hotel">Отели</label>--}}
                        {{--                                </p>--}}
                        {{--                                <p class="form-radio">--}}
                        {{--                                    <input type="radio" id="rest" name="users-ad_type">--}}
                        {{--                                    <label for="rest">Базы отдыха</label>--}}
                        {{--                                </p>--}}
                        {{--                            </div>--}}
                        {{--                        </div>--}}
                    </form>
                </div>

                <div class="admin-content_list-container">
                    <div class="admin-content_list">
                        <div class="admin-content_list-header">
                            <div class="admin-content_list-row">
                                <ul>
                                    <li>ID</li>
                                    <li>Имя</li>
                                    <li>Фамилия</li>
                                    <li>E-mail</li>
                                    <li>Телефон</li>
                                    <li>Баланс</li>
                                    <li>Статус</li>
                                    <li></li>
                                </ul>
                            </div>
                        </div>
                        <div class="admin-content_list-body">
                            @foreach($pagination->items() as $item)
                                <div class="admin-content_list-row">
                                    <ul>
                                        <li>{{$item->id}}</li>
                                        <li>{{$item->first_name}}</li>
                                        <li>{{$item->last_name}}</li>
                                        <li>{{$item->email}}</li>
                                        <li>{{$item->phone}}</li>
                                        <li>{{$item->balance > 0 ? $item->balance : 0}} ₽</li>
                                        <li>{{$item->is_active ? 'Активный' : 'Заблокированный'}}</li>
                                        <li>
                                            <div class="menu-drop">
                                                <div class="menu-drop_burger">
                                                    <span></span>
                                                    <span></span>
                                                    <span></span>
                                                </div>

                                                <ul class="menu-drop_list">
                                                    @if($item->is_active)
                                                        <li class="menu-drop_list-item"><a
                                                                    href="{{route('admin.user.action',$item->id)}}?action=inactive">Заблокировать</a>
                                                        </li>
                                                    @else
                                                        <li class="menu-drop_list-item"><a
                                                                    href="{{route('admin.user.action',$item->id)}}?action=active">Разблокировать</a>
                                                        </li>
                                                    @endif
                                                        <li class="menu-drop_list-item"><a class="_question_alert"
                                                                href="{{route('admin.user.action',$item->id)}}?action=delete">Удалить</a>
                                                        </li>
                                                    <li class="menu-drop_list-item"><a
                                                                href="{{route('admin.userObject.index')}}?search_type=user_id&search_text={{$item->id}}">Перейти
                                                            к объектам</a></li>
                                                    <li class="menu-drop_list-item"><a href="{{route('admin.user.form',$item->id)}}">Редактировать</a></li>
                                                </ul>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                @include('admin.partials.pagination')
            </div>
        </div>
    </div>
@endsection